vim.keymap.set('n', '<Leader>1', '<Cmd>BufferGoto 1<CR>', opts)
vim.keymap.set('n', '<Leader>2', '<Cmd>BufferGoto 2<CR>', opts)
vim.keymap.set('n', '<Leader>3', '<Cmd>BufferGoto 3<CR>', opts)
vim.keymap.set('n', '<Leader>4', '<Cmd>BufferGoto 4<CR>', opts)
vim.keymap.set('n', '<Leader>5', '<Cmd>BufferGoto 5<CR>', opts)
vim.keymap.set('n', '<Leader>6', '<Cmd>BufferGoto 6<CR>', opts)
vim.keymap.set('n', '<Leader>7', '<Cmd>BufferGoto 7<CR>', opts)
vim.keymap.set('n', '<Leader>8', '<Cmd>BufferGoto 8<CR>', opts)
vim.keymap.set('n', '<Leader>9', '<Cmd>BufferGoto 9<CR>', opts)
vim.keymap.set('n', '<Leader>0', '<Cmd>BufferLast<CR>', opts)
